CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE SCHEMA IF NOT EXISTS iam;
CREATE SCHEMA IF NOT EXISTS grimis_core;
CREATE SCHEMA IF NOT EXISTS grimis_risk;
CREATE SCHEMA IF NOT EXISTS grimis_incident;
CREATE SCHEMA IF NOT EXISTS grimis_ai;
CREATE SCHEMA IF NOT EXISTS grimis_log;