-- AIDAA planning tables. Safe to rerun. Run after aidaa_core_master.sql.

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS aidaa_core.ref_funding_source (funding_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), funding_code varchar(30) NOT NULL UNIQUE, funding_name varchar(200) NOT NULL, fiscal_year int NOT NULL, funding_type varchar(30) NOT NULL CHECK (funding_type IN ('budget','additional_financing','paid_by_auditee','other')), ceiling_amount numeric(18,2), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id));

CREATE TABLE IF NOT EXISTS aidaa_core.funding_document (doc_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), funding_id uuid NOT NULL REFERENCES aidaa_core.ref_funding_source(funding_id) ON DELETE CASCADE, doc_type varchar(50) NOT NULL, doc_no varchar(100), doc_date date, doc_url varchar(500) NOT NULL, uploaded_by uuid REFERENCES iam.users(user_id), uploaded_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS aidaa_core.audit_plan (plan_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_no varchar(50) NOT NULL UNIQUE, fiscal_year int NOT NULL, unit_id uuid NOT NULL REFERENCES aidaa_core.ref_auditable_unit(unit_id), type_id uuid NOT NULL REFERENCES aidaa_core.ref_audit_type(type_id), period_start date NOT NULL, period_end date NOT NULL, planned_auditors int NOT NULL DEFAULT 1, planned_days int NOT NULL DEFAULT 1, budget_mode varchar(20) NOT NULL DEFAULT 'lumpsum' CHECK (budget_mode IN ('lumpsum','detailed')), lumpsum_amount numeric(18,2) NOT NULL DEFAULT 0 CHECK (lumpsum_amount >= 0), status varchar(20) NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','approved','ai_planned','ai_approved','finished')), current_version_no int NOT NULL DEFAULT 0, is_closed boolean NOT NULL DEFAULT false, notes text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), CHECK (period_end >= period_start));

CREATE TABLE IF NOT EXISTS aidaa_core.audit_plan_member (plan_member_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid NOT NULL REFERENCES aidaa_core.audit_plan(plan_id) ON DELETE CASCADE, auditor_id uuid NOT NULL REFERENCES aidaa_core.auditor(auditor_id), assignment_role varchar(20) NOT NULL CHECK (assignment_role IN ('supervisor','leader','member')), is_budget_drafter boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), UNIQUE (plan_id, auditor_id));

CREATE TABLE IF NOT EXISTS aidaa_core.audit_plan_version (version_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid NOT NULL REFERENCES aidaa_core.audit_plan(plan_id) ON DELETE CASCADE, version_no int NOT NULL, budget_mode varchar(20) NOT NULL CHECK (budget_mode IN ('lumpsum','detailed')), total_amount numeric(18,2) NOT NULL DEFAULT 0, snapshot jsonb NOT NULL, source varchar(20) NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','ai_suggestion')), approval_status varchar(20) NOT NULL DEFAULT 'pending' CHECK (approval_status IN ('pending','approved','rejected')), approved_by uuid REFERENCES iam.users(user_id), approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), UNIQUE (plan_id, version_no));

CREATE TABLE IF NOT EXISTS aidaa_core.assignment (assignment_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_no varchar(100) NOT NULL UNIQUE, plan_id uuid REFERENCES aidaa_core.audit_plan(plan_id), unit_id uuid NOT NULL REFERENCES aidaa_core.ref_auditable_unit(unit_id), type_id uuid NOT NULL REFERENCES aidaa_core.ref_audit_type(type_id), start_date date NOT NULL, end_date date NOT NULL, assignment_doc_url varchar(500), assignment_doc_name varchar(255), status varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','issued','ongoing','finished','cancelled')), issued_by uuid REFERENCES iam.users(user_id), issued_at timestamptz, notes text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), CHECK (end_date >= start_date));

CREATE TABLE IF NOT EXISTS aidaa_core.assignment_funding (assignment_funding_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES aidaa_core.assignment(assignment_id) ON DELETE CASCADE, funding_id uuid NOT NULL REFERENCES aidaa_core.ref_funding_source(funding_id), amount numeric(18,2) NOT NULL CHECK (amount >= 0), notes text, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), UNIQUE (assignment_id, funding_id));

CREATE TABLE IF NOT EXISTS aidaa_core.assignment_member (member_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES aidaa_core.assignment(assignment_id) ON DELETE CASCADE, auditor_id uuid NOT NULL REFERENCES aidaa_core.auditor(auditor_id), role varchar(20) NOT NULL CHECK (role IN ('supervisor','leader','member')), start_date date NOT NULL, end_date date, end_reason varchar(200), created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), CHECK (end_date IS NULL OR end_date >= start_date));

CREATE UNIQUE INDEX IF NOT EXISTS uq_assignment_member_active ON aidaa_core.assignment_member(assignment_id, auditor_id) WHERE end_date IS NULL;

CREATE TABLE IF NOT EXISTS aidaa_core.assignment_visit (visit_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES aidaa_core.assignment(assignment_id) ON DELETE CASCADE, location_id uuid NOT NULL REFERENCES aidaa_core.ref_location(location_id), visit_start date NOT NULL, visit_end date NOT NULL, purpose text, status varchar(20) NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','confirmed','cancelled')), cancel_reason varchar(200), created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), CHECK (visit_end >= visit_start));

CREATE TABLE IF NOT EXISTS aidaa_core.visit_attendee (attendee_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), visit_id uuid NOT NULL REFERENCES aidaa_core.assignment_visit(visit_id) ON DELETE CASCADE, auditor_id uuid NOT NULL REFERENCES aidaa_core.auditor(auditor_id), UNIQUE (visit_id, auditor_id));

CREATE TABLE IF NOT EXISTS aidaa_core.assignment_trip_leg (leg_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES aidaa_core.assignment(assignment_id) ON DELETE CASCADE, auditor_id uuid NOT NULL REFERENCES aidaa_core.auditor(auditor_id), leg_no int NOT NULL, origin_location_id uuid NOT NULL REFERENCES aidaa_core.ref_location(location_id), destination_location_id uuid NOT NULL REFERENCES aidaa_core.ref_location(location_id), mode varchar(20) NOT NULL CHECK (mode IN ('plane','bus','boat','train','car','other')), depart_at timestamptz, arrive_at timestamptz, estimated_cost numeric(18,2) NOT NULL DEFAULT 0 CHECK (estimated_cost >= 0), actual_cost numeric(18,2) CHECK (actual_cost >= 0), status varchar(20) NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','confirmed','cancelled')), created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), UNIQUE (assignment_id, auditor_id, leg_no), CHECK (arrive_at IS NULL OR depart_at IS NULL OR arrive_at >= depart_at));

CREATE TABLE IF NOT EXISTS aidaa_core.budget_line (line_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid REFERENCES aidaa_core.audit_plan(plan_id) ON DELETE CASCADE, assignment_id uuid REFERENCES aidaa_core.assignment(assignment_id) ON DELETE CASCADE, version_no int NOT NULL DEFAULT 1, auditor_id uuid REFERENCES aidaa_core.auditor(auditor_id), component_id uuid NOT NULL REFERENCES aidaa_core.ref_cost_component(component_id), location_id uuid REFERENCES aidaa_core.ref_location(location_id), rate_id uuid REFERENCES aidaa_core.ref_cost_rate(rate_id), trip_leg_id uuid REFERENCES aidaa_core.assignment_trip_leg(leg_id) ON DELETE SET NULL, copied_from_line_id uuid REFERENCES aidaa_core.budget_line(line_id), quantity numeric(12,2) NOT NULL DEFAULT 1 CHECK (quantity >= 0), unit_rate numeric(18,2) NOT NULL DEFAULT 0 CHECK (unit_rate >= 0), amount numeric(18,2) GENERATED ALWAYS AS (quantity * unit_rate) STORED, basis varchar(20) NOT NULL DEFAULT 'standard' CHECK (basis IN ('standard','at_cost')), source varchar(20) NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','ai_suggestion')), approval_status varchar(20) NOT NULL DEFAULT 'draft' CHECK (approval_status IN ('draft','pending','approved','rejected')), notes text, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), CHECK ((plan_id IS NOT NULL)::int + (assignment_id IS NOT NULL)::int = 1));

CREATE TABLE IF NOT EXISTS aidaa_core.auditor_schedule (schedule_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), auditor_id uuid NOT NULL REFERENCES aidaa_core.auditor(auditor_id), assignment_id uuid NOT NULL REFERENCES aidaa_core.assignment(assignment_id) ON DELETE CASCADE, kind varchar(10) NOT NULL CHECK (kind IN ('visit','travel')), visit_id uuid REFERENCES aidaa_core.assignment_visit(visit_id) ON DELETE CASCADE, leg_id uuid REFERENCES aidaa_core.assignment_trip_leg(leg_id) ON DELETE CASCADE, location_id uuid REFERENCES aidaa_core.ref_location(location_id), period daterange NOT NULL, status varchar(20) NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed','cancelled')), created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), EXCLUDE USING gist (auditor_id WITH =, period WITH &&) WHERE (status = 'confirmed'));

ALTER TABLE aidaa_core.library_pka ADD COLUMN IF NOT EXISTS source_assignment_id uuid REFERENCES aidaa_core.assignment(assignment_id);