-- AIDAA master data tables. Safe to rerun. Only FKs out of iam: org_id and user_id.

CREATE SCHEMA IF NOT EXISTS aidaa_core;

CREATE TABLE IF NOT EXISTS aidaa_core.ref_location (location_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), location_code varchar(30) NOT NULL UNIQUE, location_name varchar(150) NOT NULL, parent_location_id uuid REFERENCES aidaa_core.ref_location(location_id), is_branch_office boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id));

CREATE TABLE IF NOT EXISTS aidaa_core.ref_audit_type (type_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), type_code varchar(30) NOT NULL UNIQUE, type_name varchar(150) NOT NULL, description text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id));

CREATE TABLE IF NOT EXISTS aidaa_core.ref_auditable_unit (unit_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid REFERENCES iam.organizations(org_id), unit_code varchar(30) NOT NULL UNIQUE, unit_name varchar(200) NOT NULL, unit_type varchar(50), location_id uuid REFERENCES aidaa_core.ref_location(location_id), risk_score numeric(6,2), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id));

CREATE TABLE IF NOT EXISTS aidaa_core.ref_cost_component (component_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), component_code varchar(30) NOT NULL UNIQUE, component_name varchar(150) NOT NULL, calc_basis varchar(20) NOT NULL CHECK (calc_basis IN ('per_day_worked','per_travel_day','per_night','at_cost','fixed')), sort_order int NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id));

CREATE TABLE IF NOT EXISTS aidaa_core.ref_cost_rate (rate_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), component_id uuid NOT NULL REFERENCES aidaa_core.ref_cost_component(component_id), location_id uuid REFERENCES aidaa_core.ref_location(location_id), grade varchar(30), amount numeric(18,2) NOT NULL CHECK (amount >= 0), effective_from date NOT NULL, effective_to date, approval_status varchar(20) NOT NULL DEFAULT 'draft' CHECK (approval_status IN ('draft','pending','approved','rejected')), approved_by uuid REFERENCES iam.users(user_id), approved_at timestamptz, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), CHECK (effective_to IS NULL OR effective_to >= effective_from));

CREATE TABLE IF NOT EXISTS aidaa_core.auditor (auditor_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES iam.users(user_id), home_org_id uuid REFERENCES iam.organizations(org_id), home_location_id uuid REFERENCES aidaa_core.ref_location(location_id), employee_no varchar(50), grade varchar(30), status varchar(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','leave','resigned')), joined_date date, left_date date, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id));

CREATE TABLE IF NOT EXISTS aidaa_core.expertise (expertise_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), auditor_id uuid NOT NULL REFERENCES aidaa_core.auditor(auditor_id), expertise_type varchar(30) NOT NULL CHECK (expertise_type IN ('certification','degree','training','past_experience','internal_experience')), title varchar(200) NOT NULL, issuer varchar(200), issued_date date, expiry_date date, type_id uuid REFERENCES aidaa_core.ref_audit_type(type_id), points numeric(8,2) NOT NULL DEFAULT 0, source varchar(20) NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','system_credit')), verification_status varchar(20) NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending','verified','rejected')), verified_by uuid REFERENCES iam.users(user_id), verified_at timestamptz, reject_reason text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id));

CREATE TABLE IF NOT EXISTS aidaa_core.expertise_document (doc_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), expertise_id uuid NOT NULL REFERENCES aidaa_core.expertise(expertise_id) ON DELETE CASCADE, file_name varchar(255) NOT NULL, file_path varchar(500) NOT NULL, uploaded_by uuid REFERENCES iam.users(user_id), uploaded_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS aidaa_core.library_pka (library_pka_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), type_id uuid NOT NULL REFERENCES aidaa_core.ref_audit_type(type_id), pka_code varchar(50) NOT NULL UNIQUE, title varchar(250) NOT NULL, objective text, default_hours numeric(8,2), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id));

CREATE TABLE IF NOT EXISTS aidaa_core.library_procedure (procedure_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), library_pka_id uuid NOT NULL REFERENCES aidaa_core.library_pka(library_pka_id) ON DELETE CASCADE, step_no int NOT NULL, procedure_text text NOT NULL, expected_evidence text, estimated_hours numeric(8,2), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), UNIQUE (library_pka_id, step_no));