-- AIDAA execution, finding, report tables, deviation view, review tiers. Safe to rerun. Run after aidaa_ai.sql.

ALTER TABLE aidaa_core.approval_step ADD COLUMN IF NOT EXISTS can_skip boolean NOT NULL DEFAULT false;

ALTER TABLE aidaa_core.approval_task DROP CONSTRAINT IF EXISTS approval_task_status_check;
ALTER TABLE aidaa_core.approval_task ADD CONSTRAINT approval_task_status_check CHECK (status IN ('pending','approved','rejected','returned','cancelled','skipped'));
ALTER TABLE aidaa_core.approval_task DROP CONSTRAINT IF EXISTS ck_task_skip_reason;
ALTER TABLE aidaa_core.approval_task ADD CONSTRAINT ck_task_skip_reason CHECK (status <> 'skipped' OR length(btrim(COALESCE(decision_note,''))) > 0);

ALTER TABLE aidaa_log.approval_log DROP CONSTRAINT IF EXISTS approval_log_decision_check;
ALTER TABLE aidaa_log.approval_log ADD CONSTRAINT approval_log_decision_check CHECK (decision IN ('submitted','approved','rejected','returned','skipped'));
ALTER TABLE aidaa_log.approval_log DROP CONSTRAINT IF EXISTS ck_log_skip_reason;
ALTER TABLE aidaa_log.approval_log ADD CONSTRAINT ck_log_skip_reason CHECK (decision <> 'skipped' OR length(btrim(COALESCE(reason,''))) > 0);

CREATE TABLE IF NOT EXISTS aidaa_core.pka (pka_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES aidaa_core.assignment(assignment_id) ON DELETE CASCADE, library_pka_id uuid REFERENCES aidaa_core.library_pka(library_pka_id), pka_code varchar(50), title varchar(250) NOT NULL, objective text, assigned_auditor_id uuid REFERENCES aidaa_core.auditor(auditor_id), planned_hours numeric(8,2) NOT NULL DEFAULT 0 CHECK (planned_hours >= 0), actual_hours numeric(8,2) CHECK (actual_hours >= 0), status varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending','approved','in_progress','done')), is_skipped boolean NOT NULL DEFAULT false, skip_reason text, source varchar(20) NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','library','ai_suggestion')), ai_suggestion_id uuid REFERENCES aidaa_ai.ai_suggestion(suggestion_id), approved_by uuid REFERENCES iam.users(user_id), approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), CHECK (NOT is_skipped OR skip_reason IS NOT NULL));

CREATE TABLE IF NOT EXISTS aidaa_core.exe_procedure (procedure_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), pka_id uuid NOT NULL REFERENCES aidaa_core.pka(pka_id) ON DELETE CASCADE, library_procedure_id uuid REFERENCES aidaa_core.library_procedure(procedure_id), step_no int NOT NULL, procedure_text text NOT NULL, is_skipped boolean NOT NULL DEFAULT false, skip_reason text, executed_by uuid REFERENCES aidaa_core.auditor(auditor_id), executed_at timestamptz, conclusion text, result varchar(20) CHECK (result IN ('no_exception','exception')), status varchar(25) NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','in_progress','done','leader_reviewed','supervisor_reviewed')), leader_reviewed_by uuid REFERENCES iam.users(user_id), leader_reviewed_at timestamptz, supervisor_reviewed_by uuid REFERENCES iam.users(user_id), supervisor_reviewed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), UNIQUE (pka_id, step_no), CHECK (NOT is_skipped OR skip_reason IS NOT NULL));

CREATE TABLE IF NOT EXISTS aidaa_core.working_paper (paper_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), procedure_id uuid NOT NULL REFERENCES aidaa_core.exe_procedure(procedure_id) ON DELETE CASCADE, title varchar(250) NOT NULL, file_url varchar(500) NOT NULL, file_name varchar(255), notes text, uploaded_by uuid REFERENCES iam.users(user_id), uploaded_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id));

CREATE TABLE IF NOT EXISTS aidaa_core.finding (finding_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES aidaa_core.assignment(assignment_id) ON DELETE CASCADE, procedure_id uuid REFERENCES aidaa_core.exe_procedure(procedure_id) ON DELETE SET NULL, finding_no varchar(30) NOT NULL, title varchar(250) NOT NULL, description text, criteria text, materiality_amount numeric(18,2) NOT NULL DEFAULT 0 CHECK (materiality_amount >= 0), communicated_at timestamptz, response_due_date date, status varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','leader_reviewed','approved','communicated','responded','open','closed')), created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), UNIQUE (assignment_id, finding_no), CHECK (status NOT IN ('communicated','responded','open','closed') OR (communicated_at IS NOT NULL AND response_due_date IS NOT NULL)));

CREATE TABLE IF NOT EXISTS aidaa_core.finding_response (response_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), finding_id uuid NOT NULL REFERENCES aidaa_core.finding(finding_id) ON DELETE CASCADE, round_no int NOT NULL, direction varchar(25) NOT NULL CHECK (direction IN ('auditor_communication','auditee_response')), stance varchar(20) CHECK (stance IN ('agree','partially_agree','disagree')), message text, action_plan text, target_date date, evidence_url varchar(500), responded_by uuid REFERENCES iam.users(user_id), responded_at timestamptz NOT NULL DEFAULT now(), UNIQUE (finding_id, round_no), CHECK (direction = 'auditor_communication' OR stance IS NOT NULL));

CREATE TABLE IF NOT EXISTS aidaa_core.rekomend (rekomend_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), finding_id uuid NOT NULL REFERENCES aidaa_core.finding(finding_id) ON DELETE CASCADE, rekomend_no varchar(30) NOT NULL, recommendation_text text NOT NULL, due_date date, status varchar(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','closed')), followup_note text, followup_url varchar(500), followup_by uuid REFERENCES iam.users(user_id), followup_at timestamptz, closed_during_audit boolean NOT NULL DEFAULT false, closed_by uuid REFERENCES iam.users(user_id), closed_at timestamptz, last_monitored_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), UNIQUE (finding_id, rekomend_no));

CREATE TABLE IF NOT EXISTS aidaa_core.audit_report (report_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES aidaa_core.assignment(assignment_id) ON DELETE CASCADE, version_no int NOT NULL DEFAULT 1, opinion text, summary text, materiality_threshold_pct numeric(5,2) NOT NULL DEFAULT 5 CHECK (materiality_threshold_pct >= 0), total_open_materiality numeric(18,2) NOT NULL DEFAULT 0, report_url varchar(500), source varchar(20) NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','ai_suggestion')), ai_suggestion_id uuid REFERENCES aidaa_ai.ai_suggestion(suggestion_id), status varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','review','approved','final')), created_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES iam.users(user_id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES iam.users(user_id), UNIQUE (assignment_id, version_no));

CREATE OR REPLACE VIEW aidaa_core.v_plan_deviation AS SELECT a.assignment_id, a.assignment_no, a.plan_id, p.plan_no, (a.plan_id IS NULL) AS is_unplanned, p.planned_auditors, (SELECT count(*) FROM aidaa_core.assignment_member m WHERE m.assignment_id = a.assignment_id AND m.end_date IS NULL) AS actual_auditors, p.planned_days, (a.end_date - a.start_date + 1) AS actual_days, (p.planned_auditors * p.planned_days) AS planned_man_days, (SELECT COALESCE(sum(COALESCE(m.end_date, a.end_date) - m.start_date + 1), 0) FROM aidaa_core.assignment_member m WHERE m.assignment_id = a.assignment_id) AS actual_man_days, (SELECT v.total_amount FROM aidaa_core.audit_plan_version v WHERE v.plan_id = p.plan_id AND v.approval_status = 'approved' ORDER BY v.version_no DESC LIMIT 1) AS planned_budget, (SELECT COALESCE(sum(b.amount), 0) FROM aidaa_core.budget_line b WHERE b.assignment_id = a.assignment_id AND b.approval_status <> 'rejected') AS actual_budget, CASE WHEN a.plan_id IS NULL THEN NULL ELSE NOT EXISTS (SELECT 1 FROM aidaa_core.audit_plan_member pm JOIN aidaa_core.assignment_member am ON am.auditor_id = pm.auditor_id AND am.assignment_id = a.assignment_id AND am.role = 'leader' AND am.end_date IS NULL WHERE pm.plan_id = a.plan_id AND pm.assignment_role = 'leader') END AS leader_changed, (SELECT COALESCE(sum(k.planned_hours), 0) / 8 FROM aidaa_core.pka k WHERE k.assignment_id = a.assignment_id AND NOT k.is_skipped) AS pka_planned_days FROM aidaa_core.assignment a LEFT JOIN aidaa_core.audit_plan p ON p.plan_id = a.plan_id;

INSERT INTO aidaa_core.approval_step (record_type, step_no, step_code, approver_kind, approver_role, can_skip) VALUES ('procedure',1,'leader_review','assignment_role','leader',false),('procedure',2,'supervisor_review','assignment_role','supervisor',true),('finding',1,'leader_review','assignment_role','leader',false),('finding',2,'supervisor_approve','assignment_role','supervisor',false) ON CONFLICT (record_type, step_no) DO NOTHING;

ALTER TABLE aidaa_core.audit_plan ADD COLUMN IF NOT EXISTS owner_org_id uuid NOT NULL REFERENCES iam.organizations(org_id);
ALTER TABLE aidaa_core.assignment ADD COLUMN IF NOT EXISTS owner_org_id uuid NOT NULL REFERENCES iam.organizations(org_id);